{
  "version": "3.9",
  "services": {
    "backend": {
      "build": "./backend",
      "ports": [
        "8080:8080"
      ]
    },
    "frontend": {
      "build": "./frontend",
      "ports": [
        "3000:80"
      ],
      "environment": {
        "VITE_API_BASE": "http://localhost:8080"
      },
      "depends_on": [
        "backend"
      ]
    },
    "prometheus": {
      "image": "prom/prometheus:latest",
      "ports": [
        "9090:9090"
      ],
      "volumes": [
        "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
      ]
    },
    "grafana": {
      "image": "grafana/grafana:latest",
      "ports": [
        "3001:3000"
      ],
      "volumes": [
        "./monitoring/datasources:/etc/grafana/provisioning/datasources",
        "./monitoring/dashboards:/var/lib/grafana/dashboards"
      ],
      "environment": {
        "GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH": "/var/lib/grafana/dashboards/pulseboard-overview.json"
      }
    }
  }
}