name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend test/build
        run: |
          cd backend
          npm ci
          npm test || true
      - name: Frontend build
        run: |
          cd frontend
          npm ci
          npm run build
