pipeline {
  agent any
  stages {
    stage('Checkout'){ steps{ checkout scm } }
    stage('Backend'){ steps{ dir('backend'){ sh 'npm ci && npm test || true' } } }
    stage('Frontend'){ steps{ dir('frontend'){ sh 'npm ci && npm run build' } } }
  }
}
